%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: camera
#Image Downsample need
down_sample: 1
# The size of the image after scaling, the current scaling ratio is 0.25
image_width: 480 # origin 1920
image_height: 300 # origin 1200
focal_length: 460 #920

distortion_parameters:
   k1: -0.0750010191617321
   k2: 0.180935113438105
   p1: 0.000369752156726844
   p2: -0.000227955828246710
projection_parameters:
   fx: 430.620613181 #1722.48245272370
   fy: 430.512993774 #1722.05197509732
   cx: 241.678159696 #966.712638783214
   cy: 151.2910798   #605.164319198491

# Rotation from lidar frame to camera center, cam^R_LiDAR (aka R_CL)
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-0.999894882597964,-0.0119984253697330,-0.00814011935115670,
         -0.00802895822022270,-0.00928387805710237,0.999924669881746,
         -0.0120730934023575,0.999884917076394,0.00918656730395798]
# Translation from lidar frame to camera center, cam^T_LiDAR
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [0.358384116216476,0.173661815022988,-0.0469106849352510]

#feature traker parameters
max_keyline_count: 80 
keyline_detector_octaves: 1
keyline_detector_scale: 1.2

lbd_descriptor_width_of_band: 7

max_keypoint_count: 50
min_keypoint_dist: 40
F_threshold: 1.0
sliding_window_size: 5

#laser registrator parameters
laser_scan_number: 16
horizon_scans: 1800
minimum_range: 0.1
angle_res_x: 0.2
angle_res_y: 2.0
angle_bottom: 15.1
crop_near: 1.0
crop_far: 80

edge_threshold: 5
surf_threshold: 3    # for uav, to get more points, this should set larger (which will improve ndt+icp accuracy)
nearest_feature_search_dist: 25
occlude_threshold: 0.3
range_diff_threshold: 0.02

distortion: 0  # There are some problems in the implementation of the algorithm, it is best set 0
scan_period: 0.1   # The time of one lidar scan, unit is second
distance_sq_threshold: 25
nearby_scan: 2.5
visual_weight_max: 0.5  # [0,1]   # The maximum weight coefficient of the visual part residual item in the front-end odometry part

# submap para
submap_length: 40
keep_squre_distance: 5000 #3000

# thumbnail para
ndt_resolution_thumbnail: 2.0
ndt_resolution_match: 5 # for uav, this value should not be too small, otherwise will bring seg fault in ndt
need_check_direction: 1 # On a drone, if your equipment (default is camera) Z axis is facing down, such as the installation 
                        # method in GrAco dataset(45 degree face down), set 1, otherwise set 0

# output odom para, tum format
need_pub_odom: 1
out_odom_path: /home/sysu-rapid/gacm_output/data/testSavemap/   # must end with "/"

# for memory save
cache_path: /home/sysu-rapid/gacm_output/cache/     # must end with "/"

# no use / deprecate
gt_path: deprecate
gt_start_time: 0
out_gt_path: deprecate
air_gps: 0
